### ISSUE TITLE
Optimization TODOs: Checklist

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/lvars#100]
- Make mutable fields strict so they can unbox
  - [x] for the `State` structure
  - [ ] for other miscellaneous structures in the Scheduler
  - [ ] confirm impact in the [criterion microbenchmarks](https://github.com/iu-parfunc/lvars/blob/master/haskell/lvish/tests/Bench.hs)
- Bag related:
  - [ ] Issue #99 is an optimization
  - [ ] Investigate whether a mutable bit vector could work for the listener bag.
